<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf8" />
        <title><?=$title; ?></title>
        <script type="text/javascript">
        </script>
    </head>
    
    <body>
        <div>
            <h2>Welcome to Index page</h2>
            <p>Hello world!</p>
            <p>Your location: <?=$ip; ?></p>
        </div>
        <div>Path for <a href="/user">User</a></div>
    </body>
</html>